_wandb:
    value:
        cli_version: 0.18.3
        m: []
        python_version: 3.12.3
        t:
            "1":
                - 55
            "2":
                - 55
            "3":
                - 2
                - 17
                - 23
                - 55
            "4": 3.12.3
            "5": 0.18.3
            "8":
                - 5
            "12": 0.18.3
            "13": darwin-arm64
activation:
    value: linear
epochs:
    value: 200
hidden_layers:
    value:
        - 20
        - 20
learning_rate:
    value: 0.01
optimizer:
    value: sgd
