wandb_version: 1

activation:
  value: relu
epochs:
  value: 100
hidden_layers:
  value:
  - 40
  - 35
  - 30
  - 25
  - 20
  - 15
  - 10
  - 10
learning_rate:
  value: 0.0008
optimizer:
  value: mini_batch
