wandb_version: 1

activation:
  value: relu
epochs:
  value: 50
hidden_layers:
  value:
  - 60
  - 60
  - 50
  - 50
  - 40
  - 40
  - 30
  - 30
learning_rate:
  value: 0.0008
optimizer:
  value: mini_batch
