wandb_version: 1

activation:
  value: relu
epochs:
  value: 50
hidden_layers:
  value:
  - 40
  - 40
  - 30
  - 30
  - 25
  - 25
  - 20
  - 20
learning_rate:
  value: 0.001
optimizer:
  value: mini_batch
