wandb_version: 1

activation:
  value: tanh
epochs:
  value: 100
hidden_layers:
  value:
  - 60
  - 60
  - 50
  - 50
  - 40
  - 40
  - 30
  - 30
learning_rate:
  value: 0.001
optimizer:
  value: batch
