wandb_version: 1

activation:
  value: tanh
epochs:
  value: 200
hidden_layers:
  value:
  - 20
  - 20
  - 20
  - 20
  - 20
  - 20
  - 20
  - 20
learning_rate:
  value: 0.0008
optimizer:
  value: sgd
